version: '3.7'


services:
#  db:
#    image: postgres
#    env_file:
#      - .env
  es:
    image: 'elasticsearch:6.8.16'
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
